# Change these first
owner: PawaraGunathilaka # Your GitHub organization or username, where this repository lives
repo: upptime-test # The name of this repository

sites:
  - name: Insighture
    url: https://www.insighture.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-test
  name: Upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
